### ISSUE TITLE
Initializing submodules fails

### ISSUE THREAD

**Issue by andrewthad** [tweag/ghc#165]
Here's the error:

```
$ git submodule update --init
error: Server does not allow request for unadvertised object 2a71ca72b591233a019054e45e23e3e027418099
Fetched in submodule path 'utils/haddock', but it did not contain 2a71ca72b591233a019054e45e23e3e027418099. Direct fetching of that commit failed.
```

The `utils/haddock` submodule should probably be bumped to something that exists.

**Comment by aspiwack** [comment]
Hi @andrewthad 

Submodules are tiresome, I'm afraid. What happens is that we have our own copy of the haddock submodule because it depends on GHC. The simplest solution is to `git submodule sync utils/haddock` before calling `git submodule update` again.

(be careful: if you `sync` globally it will be incorrect too, unless you are on a detached head)

**Comment by andrewthad** [comment]
That does the trick. Thanks!
