### ISSUE TITLE
Some wrappers inline too early (T15840a)

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#211]
T15840a is broken because of this (though what it is supposed to test works).

What happens here is that at the end of desugaring we have, as expected:

```haskell
main :: IO ()
[LclIdX]
main
  = case Main.$WMkT @ 'Omega (GHC.Types.$WTrue @ 'Omega) of
    { MkT x_a12Y ->
    f x_a12Y
    }
```

But after the first simplifier (initial phase, immediately after desugaring), we have

```haskell
main :: IO ()
[LclIdX,
Arity=1,
Unf=Unf{Src=<vanilla>, TopLvl=True, Value=True, ConLike=True,
        WorkFree=True, Expandable=True, Guidance=IF_ARGS [] 20 60}]
main = f GHC.Types.True
```

We expect case-of-known-constructor to reduce the `case $WMkT …`, but the `$WTrue` should not be inlined, as it's not subject to any case. I'm not sure what's happening here yet.

PS: it breaks the test because the rule refers to `True`'s wrapper:

```haskell
 RULES: "non-det" [~0]
           forall (@ (n_a1wM :: GHC.Types.Multiplicity)).
             f (GHC.Types.$WTrue @ n_a1wM)
             = g]
```

**Comment by monoidal** [comment]
Here's what's happening. We have

```
{-# RULES "non-det" [~0] f $WTrue = g #-}
data T = MkT !Bool
main = case $WMkT $WTrue of
  MkT x -> f x
```

`exprIsConApp_maybe` is checking if `$WMkT $WTrue` is a constructor application; since `MkT` is strict, the answer is `MkT foo` where `foo` is bound by a case float `case $WTrue of foo`. So the code is optimized to

```
main = case $WTrue of
   foo -> f foo
```

`exprIsConApp_maybe is called again, and answers that `$WTrue` this is an application of the `True` constructor. So the code becomes `main = f True`. At no point we see the expression `f $WTrue` which is needed for the rule to fire.

**Comment by aspiwack** [comment]
We will have to be creative in adapting the test, then :slightly_smiling_face:
