### ISSUE TITLE
Measure the build time of the major build phases

### ISSUE THREAD

**Issue by facundominguez** [tweag/ghc#28]
Measure the time it takes to build the various steps described here.
https://ghc.haskell.org/trac/ghc/wiki/Building/Using#Orderofthebuild

We need measures with 1 cpu, 2 cpus and 8 cpus.

**Comment by mrkkrp** [comment]
As a point of reference, here are total build times on my machine with default settings (as it's setup on Circle CI currently):

* Total build time with `make build -j2`: `41m21.498s`.
* Total test time with `make test -j2`: `42m32.853s`.
* Total build time with `make build -j9`: `23m43.880s`.
* Total test time with `make test -j9`: `43m39.732s`.

For some reason parallelism does not help with tests.

How to split the build is a more difficult question. We can't just `cd` into a directory and call `make` because then most of the time is spent making `libraries/`:

Component       | -j2 (real) | -j9 (real)
----------------|------------|-----------
libraries       | 18m34.165s | 10m7.890s
compiler        | 2m47.945s  | ?
ghc             | 0m2.308s   | ?
rest            | 0m10.145s  | ?
tests           | 60m7.463s  | ?

(This is with build flavor `quick`, so it's faster than what is used on CI, but it gives a picture about time distribution with this approach.)

Gong to try to build stage0 / stage 1 / stage 2 and use stage freezing.

**Comment by facundominguez** [comment]
Thanks, @mrkkrp. Note that circleci is running tests with `make slowtest` so they'll take longer than here.

**Comment by mrkkrp** [comment]
Only with llvm job, with other jobs they run `make test`.

**Comment by mrkkrp** [comment]
Latest update: compiling first `libraries/` and then the rest splits the build in 27 minutes and 18 minutes. May be a good splitting point if we'll have to do it that way.

**Comment by facundominguez** [comment]
Managed to build ghc-stage1 with optimizations in 30 minutes: https://ci.appveyor.com/project/mboes/ghc/build/61

```
--- a/.appveyor.sh
+++ b/.appveyor.sh
@@ -35,7 +35,7 @@ case "$1" in
         # Build the compiler
         ./boot
         ./configure --enable-tarballs-autodownload
-        make -j2
+        make -j3 inplace/bin/ghc-stage1
         ;;
```

**Comment by facundominguez** [comment]
This build shows ghc-stage1 plus rts plus ghc-prim in a bit more than 45 minutes.
https://ci.appveyor.com/project/mboes/ghc/build/65

```
--- a/.appveyor.sh
+++ b/.appveyor.sh
@@ -35,7 +35,7 @@ case "$1" in
         # Build the compiler
         ./boot
         ./configure --enable-tarballs-autodownload
-        make -j2
+        make -j3 all_libraries/ghc-prim
         ;;
 
     "test")
```

**Comment by aspiwack** [comment]
I believe that this issue pertains to past CI issues and can be closed, correct?

**Comment by mrkkrp** [comment]
I think so.
