### ISSUE TITLE
First thing to do after merge: stop manipulating `funTyCon` with numbers

### ISSUE THREAD

**Issue by aspiwack** [tweag/ghc#449]
Inside GHC Core, there is a projection `F … A … ~ F … A' … |- A ~ A'`. The argument is referred to by its number.

It's generally fine, except that we do that manually in a handful of places where `F = FUN`. Whenever the function type changes arity, then we need to edit number everywhere.  This is was pointed out by copious tears during development of the linear types branch and by @goldfirere during the code review.

When this is merge, the first thing that should happen is to solve this issue for ever. The best proposal that I've seen so far is to make a pattern synonym to deconstruct `FunTyCon`.

**Comment by monoidal** [comment]
I've tried doing it against master: https://gitlab.haskell.org/tweag/ghc/-/commit/01d2e05be880b59e13c9252bafb5341b8e645e76 but it causes one stat test failure.

**Comment by monoidal** [comment]
I've tried again, there are still perf issues: https://gitlab.haskell.org/tweag/ghc/-/commit/0a6786461e2dbff2c09368ecc41ffd930cfe88d0/pipelines?ref=wip%2Ffuntycon-args

Ideas:
- debug whether it's because of matching or constructing
- try to use a view pattern instead, returning `Maybe (a,a,a,a,a)` or a dedicated `Yes a a a a a | No` type (one less layer of indirection)

Aside from changes made in that commit, there are magic numbers in places referencing [Function coercions] and the definition of funTyCon could have a link to FunTyConArgs.

**Comment by aspiwack** [comment]
You can try using a view pattern with `INLINE`, indeed. Probably it would be better with a record though. The extra `Maybe` is probably irrelevant if you have `INLINE`. So I don't think I'd worry about this too much. Though there is a case for the idea that each view should have its own maybe-like type.

Also, it's worth opening a discussion on gitlab on whether these performance effects are worth it or not. But probably only after the view pattern thing has been tried.

**Comment by monoidal** [comment]
Moved to https://gitlab.haskell.org/ghc/ghc/-/issues/18750.
