### ISSUE TITLE
not clear how to use after build

### ISSUE THREAD

**Issue by jwaldmann** [tweag/ghc#89]
I was building from source, following instructions in the README of this repo. When I try to run the example (also from the README) in the freshly-built ghci, the lollipop arrow is not accepted.
```
Prelude> :set -XTypeOperators 
Prelude> let frugal :: a ⊸ (a,a); frugal a = (a,a)

<interactive>:3:15: error:
    Not in scope: type constructor or class ‘⊸’
```
How can I be sure that my ghci actually does have your patches, or has them enabled?

E.g., when I `:browse` the default namespace, all the types look exactly like they would in plain `ghci`.
That's intentional - you did not linearize the Prelude?

**Comment by mpickering** [comment]
The easiest way is to use the docker image `tweag/linear-types`. I'm not sure exactly what commit it is from but it should be somewhat useful.

**Comment by jwaldmann** [comment]
I will try. (But for me, "build from source" is much easier than "use docker image".)
Am I just missing something trivial to switch on linearity?

**Comment by mpickering** [comment]
Are you using the `linear-types` branch. That might work but no guarantees..

**Comment by jwaldmann** [comment]
I do (following instructions at  https://github.com/tweag/ghc/tree/linear-types) 

I do see some lollipops, but I cannot write them. Well, the following works, and it should be enough for a presentation.
```
GHCi, version 8.5.20180529: http://www.haskell.org/ghc/  :? for help
Prelude> data T = T Bool Bool
Prelude> :t T
T :: Bool ⊸ Bool ⊸ T
Prelude> g = asTypeOf T (\ x y -> T x x)

<interactive>:3:19: error:
    • Couldn't match expected weight ‘1’ of variable ‘x’ with actual weight ‘ω’
    • In the second argument of ‘asTypeOf’, namely ‘(\ x y -> T x x)’
      In the expression: asTypeOf T (\ x y -> T x x)
      In an equation for ‘g’: g = asTypeOf T (\ x y -> T x x)

<interactive>:3:21: error:
    • Couldn't match expected weight ‘1’ of variable ‘y’ with actual weight ‘0’
    • In the second argument of ‘asTypeOf’, namely ‘(\ x y -> T x x)’
      In the expression: asTypeOf T (\ x y -> T x x)
      In an equation for ‘g’: g = asTypeOf T (\ x y -> T x x)
```

**Comment by mpickering** [comment]
Try using `->.` instead? Or otherwise turn on `-XUnicodeSyntax`.

**Comment by jwaldmann** [comment]
Ah! That's it! Thank you. 

(Might mention it in the README.)

**Comment by aspiwack** [comment]
Thanks a lot for your interest and persistence!

It seems indeed that the README is out of date, thank you for pointing it out. This is a fairly fast moving, burning-all-bridges kind of branch, so it's easy to get into this sort of situation. I will get to update the README by the end of the week. But do feel free to propose a PR by then.

> E.g., when I :browse the default namespace, all the types look exactly like they would in plain ghci.
That's intentional - you did not linearize the Prelude?

Indeed. We believe it to be too early to change anything in base. Which, at any rate, does follow a different process than changes in the compiler. However, we are writing a [linear-base](https://github.com/tweag/linear-base/) library. It's still quite preliminary. But it has a few neat things.

**Comment by aspiwack** [comment]
See #301 : the README is currently up to date.
